functional:
Пользователь должен иметь возможность искать товары по ключевому слову или категории
Пользователь должен иметь возможность фильтровать товары
Сайт должен иметь мобильную версию
Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional: 
Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
Сайт нужно протестировать на совместимость с последними версиями браузеров
Сайт должен быть доступен на различных устройствах
Сайт должен быть безопасным и защищать данные пользователя
Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
Главная страница будет открываться мгновенно
Личные данные пользователей хранятся на отдельном сервере под защитой
